baseURL = "https://gynecologistsangeeta.com"
title = "Dr. Sangeeta Pradhan"
timeZone = "Asia/Kolkata"
summaryLength = 25
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
theme = "github.com/zeon-studio/hugoplate"

[services]
[services.googleAnalytics]
ID = 'G-MEASUREMENT_ID'

[permalinks]
pages = "/:slugorcontentbasename/"

[build]
[build.buildStats]
enable = true


[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

[imaging]
quality = 80
resampleFilter = "Lanczos"

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai'
lineNumbersInTable = false

[markup.tableOfContents]
startLevel = 1
endLevel = 5
ordered = true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
lazy = true
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
lazy = true

[[params.plugins.js]]
link = "js/search.js"
lazy = false
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
lazy = false
[[params.plugins.js]]
link = "plugins/cookie.js"
lazy = false
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
lazy = true
[[params.plugins.js]]
link = "js/gallery-slider.js"
lazy = true
[[params.plugins.js]]
link = "js/accordion.js"
lazy = true
[[params.plugins.js]]
link = "js/tab.js"
lazy = true
[[params.plugins.js]]
link = "js/modal.js"
lazy = true
[[params.plugins.js]]
link = "plugins/youtube-lite.js"
lazy = true