[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Dr. Sangeeta"
url = "/about/"
weight = 2

[[main]]
name = "Research & Publications"
url = "/about/publications/"
weight = 3

[[main]]
name = "Services"
url = "/services/"
weight = 4

[[footer]]
name = "About"
url = "/about/"
weight = 1

[[footer]]
name = "Services"
url = "/services/"
weight = 2

[[footer]]
name = "Patient Rights"
url = "/privacy-policy/patients-right/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 4

[[footer]]
name = "Book Consultation"
url = "/contact/"
weight = 5